name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main

    - name: Setup yarn
      run: npm install -g yarn

    - name: Install
      run: yarn install

    - name: Build
      run: yarn build

    - name: Tests coverage
      run: yarn test:cov

    - name: Format & Lint
      run: yarn format && yarn lint

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/luizalabs:latest, ${{secrets.DOCKER_USERNAME}}/luizalabs:${{ github.sha }}
